name: Test SF Upload

on:
  workflow_dispatch:

jobs:
  test-upload:
    runs-on: ubuntu-latest

    steps:
      - name: Create Fake ZIP
        run: |
          cd /tmp
          echo "AxionOS gta4l test file" > test.txt
          zip AxionOS-TEST-gta4l.zip test.txt

      - name: Upload to SourceForge
        uses: appleboy/scp-action@v0.1.7
        with:
          host: frs.sourceforge.net
          username: mkpromvp
          key: ${{ secrets.SF_PRIVATE_KEY }}
          source: "/tmp/AxionOS-TEST-gta4l.zip"
          target: "/home/frs/project/gta4l-builds/"
